import { Grid } from '@mui/material';
import type { Metadata } from 'next';
import Header from '@/components/Header';

export const metadata: Metadata = {
  title: 'Main',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <Header />
      <body>
        <Grid item xs={12}>
          {children}
        </Grid>
      </body>
    </html>
  );
}
