import { Box, Grid } from '@mui/material';
import type { Metadata } from 'next';
import Image from 'next/image';
import extBackground from '../app/assets/images/ext-background.png';
import './globals.css';

export const metadata: Metadata = {
  title: 'Main',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>
        <Grid container>
          <Box
            sx={{
              backgroundColor: '#401d59',
              position: 'fixed',
              top: 0,
              left: 0,
              right: 0,
              bottom: 0,
              zIndex: -1,
            }}
          />
          <Image
            style={{
              position: 'fixed',
              top: 0,
              left: 0,
              right: 0,
              bottom: 0,
              objectFit: 'cover',
              objectPosition: 'left',
              width: '100%',
              height: '100%',
              zIndex: -1,
            }}
            alt=''
            src={extBackground}
          />
          {/* <Header /> */}
          <Grid item xs={12}>{children}</Grid>
        </Grid>
      </body>
    </html>
  );
}
