import Footer from "@/components/Footer";
import PurpleBackground from "@/components/PurpleBackground";
import { Grid } from "@mui/material";
import Head from "next/head";
import { items } from "../../static";
import Activity from "./component/Activity";
import Article from "./component/Article";
import Banner from "./component/Banner";
import StorageService from "./component/StorageService";
import TrendingProduct from "./component/TrendingProduct";

const Home = () => {

  return (
    <Grid xs={12} container>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Grid xs={12} container rowSpacing={6}>
        <PurpleBackground />
        <Grid item xs={12}>
          <Banner />
        </Grid>
        <Grid item xs={12}>
          <Article />
        </Grid>
        <Grid item xs={12}>
          <TrendingProduct items={items} />
        </Grid>
        <Grid item xs={12}>
          <StorageService />
        </Grid>
        <Grid item xs={12}>
          <Activity />
        </Grid>
      </Grid>
      <Grid xs={12}>
        <Footer />
      </Grid>
    </Grid>
  );
};

export default Home;
