export const staticUser = [
  { id: 1, name: "Nguyễn Văn A", email: "a@example.com", phone: "0123456789", address: "Hà Nội" },
  { id: 2, name: "Trần Thị B", email: "b@example.com", phone: "0123456788", address: "Hải Phòng" },
  { id: 3, name: "Lê Văn C", email: "c@example.com", phone: "0123456787", address: "Đà Nẵng" },
  { id: 4, name: "Phạm Thị D", email: "d@example.com", phone: "0123456786", address: "Hồ Chí Minh" },
  { id: 5, name: "Hoàng Văn E", email: "e@example.com", phone: "0123456785", address: "Cần Thơ" },
  { id: 6, name: "Nguyễn Thị F", email: "f@example.com", phone: "0123456784", address: "Bắc Ninh" },
  { id: 7, name: "Vũ Văn G", email: "g@example.com", phone: "0123456783", address: "Nam Định" },
  { id: 8, name: "Trương Thị H", email: "h@example.com", phone: "0123456782", address: "Quảng Ninh" },
  { id: 9, name: "Đỗ Văn I", email: "i@example.com", phone: "0123456781", address: "Thanh Hóa" },
  { id: 10, name: "Hà Thị J", email: "j@example.com", phone: "0123456780", address: "Nghệ An" },
  { id: 11, name: "Lâm Văn K", email: "k@example.com", phone: "0123456790", address: "Hải Dương" },
  { id: 12, name: "Ngô Thị L", email: "l@example.com", phone: "0123456791", address: "Vinh Phúc" },
  { id: 13, name: "Tạ Văn M", email: "m@example.com", phone: "0123456792", address: "Hưng Yên" },
  { id: 14, name: "Bùi Thị N", email: "n@example.com", phone: "0123456793", address: "Bắc Giang" },
  { id: 15, name: "Đặng Văn O", email: "o@example.com", phone: "0123456794", address: "Thái Bình" },
  { id: 16, name: "Nguyễn Thị P", email: "p@example.com", phone: "0123456795", address: "Hòa Bình" },
  { id: 17, name: "Hoàng Thị Q", email: "q@example.com", phone: "0123456796", address: "Lào Cai" },
  { id: 18, name: "Lê Văn R", email: "r@example.com", phone: "0123456797", address: "Tuyên Quang" },
  { id: 19, name: "Vũ Thị S", email: "s@example.com", phone: "0123456798", address: "Yên Bái" },
  { id: 20, name: "Trần Văn T", email: "t@example.com", phone: "0123456799", address: "Hưng Yên" },
];

export const staticProducts = [
  { id: 1, name: "Ghế Sofa", category: "Sofa", price: 500, stock: 10 },
  { id: 2, name: "Bàn ăn", category: "Bàn", price: 200, stock: 15 },
  { id: 3, name: "Giường ngủ", category: "Giường", price: 700, stock: 8 },
  { id: 4, name: "Tủ quần áo", category: "Tủ", price: 600, stock: 12 },
  { id: 5, name: "Bàn trà", category: "Bàn", price: 150, stock: 20 },
  { id: 6, name: "Kệ TV", category: "Kệ", price: 250, stock: 18 },
  { id: 7, name: "Ghế làm việc", category: "Ghế", price: 180, stock: 25 },
  { id: 8, name: "Bàn làm việc", category: "Bàn", price: 300, stock: 14 },
  { id: 9, name: "Tủ sách", category: "Tủ", price: 400, stock: 7 },
  { id: 10, name: "Gương trang trí", category: "Gương", price: 100, stock: 30 },
  { id: 11, name: "Bàn ngoài trời", category: "Bàn", price: 350, stock: 10 },
  { id: 12, name: "Ghế bành", category: "Ghế", price: 220, stock: 12 },
  { id: 13, name: "Tủ đầu giường", category: "Tủ", price: 150, stock: 16 },
  { id: 14, name: "Kệ sách", category: "Kệ", price: 200, stock: 19 },
  { id: 15, name: "Bàn trang điểm", category: "Bàn", price: 280, stock: 11 },
  { id: 16, name: "Ghế bập bênh", category: "Ghế", price: 130, stock: 13 },
  { id: 17, name: "Tủ giày", category: "Tủ", price: 170, stock: 14 },
  { id: 18, name: "Bàn đèn", category: "Bàn", price: 90, stock: 22 },
  { id: 19, name: "Ghế đôn", category: "Ghế", price: 75, stock: 25 },
  { id: 20, name: "Bàn ăn ngoài trời", category: "Bàn", price: 400, stock: 9 },
];

export const staticCategories = [
  { id: 1, name: "Sofa", description: "Ghế sofa và các loại ghế đệm khác." },
  { id: 2, name: "Bàn", description: "Các loại bàn bao gồm bàn ăn, bàn trà, bàn làm việc." },
  { id: 3, name: "Giường", description: "Giường ngủ và các sản phẩm liên quan." },
  { id: 4, name: "Tủ", description: "Tủ quần áo, tủ sách, tủ đầu giường, tủ giày." },
  { id: 5, name: "Kệ", description: "Kệ TV, kệ sách, kệ trang trí." },
  { id: 6, name: "Ghế", description: "Ghế làm việc, ghế bành, ghế bập bênh, ghế đôn." },
  { id: 7, name: "Gương", description: "Gương trang trí và các loại gương khác." },
];